### ISSUE TITLE
Optimize build time

### ISSUE THREAD

**Issue by lookeypl** [nfprojects/nfengine#10]
The following things could be done to improve compilation time:
- [ ] remove unsused headers (or remove some and use predeclarations)
- [x] extract project for gtest (currently, it's compiled twice: for nfCommonTest and nfCoreTest)
- [ ] experiment with precompiled headers (maybe it's not worth including all external headers into them)

**Comment by lookeypl** [comment]
Project for gtest is extracted as a part of #91

**Comment by Witek902** [comment]
I would exclude the issue from "Project reorganization" milestone. Removing all the dependencies from engine's repository will greately speedup the compilation. Other improvements (headers optimization) are low priority so they could be done later IMO.

**Comment by lookeypl** [comment]
Agreed, let's remove that from reorganization.

2014-12-03 17:41 GMT+01:00 Michał notifications@github.com:
