### ISSUE TITLE
Design renderer backend generic API

### ISSUE THREAD

**Issue by Witek902** [nfprojects/nfengine#100]
The renderer backend API must be:
- compatible with various existing technologies (Direct3D 11, OpenGL 4.5)
- prepared for upcoming technologies (Direct3D 12, Vulcan, Mantle)
- efficient (note that D3D's and OGL's API differs much, and making the backend API similar to one of them may have negative performance impact when applied to another)
- handle shaders somehow (need discussion)

**Comment by lookeypl** [comment]
The RendererInterface was introduced. Further changes are discussed on "as needed" basis. Closing.
