### ISSUE TITLE
Tests summary in XML

### ISSUE THREAD

**Issue by lookeypl** [nfprojects/nfengine#101]
Google Test outputs tests results on stdout. While right now this is not that big a deal, further on tests will take a lot of space and going through results (especially for every build configuration possible) might be difficult.

Enhance our testing framework by doing the following:
- Create a script in your preferred script language (preferably Python) to launch tests and collect XML output from them (it might be necessary to replace tests.sh/tests.bat scripts)
- Parse collected XML output and provide a summary at the end of tests
- For the sake of pre-commit script ( #59 ), tests should have an ability to supress gtest output and display summary only (then consider adding an indicator of test progress - a progress bar, a one-line info counting finished tests or sth else).
- Script should be able to pass arguments further to gtest
- Format scripts output properly:
  - Information about passed test colored in green, and about failing test colored in red
  - Indentation according to test hierarchy 
  - Max one line for each test (error message why test failed can be skipped)
  - Tests should be grouped correctly
- If any of the tests fails, provide a command to launch specificaly this failing test (remember this must be convenient - user must be able to quickly copy-paste the line and launch it)

**Comment by mkulagowski** [comment]
Should the script be multiplatform? As far as the script alone it doesn't matter, but there are differences in formatting data outputted to console. I can do this myself or just use sth like colorama (https://pypi.python.org/pypi/colorama).

Also gtest output XMLs are really simple and so, easy to go through: 
https://code.google.com/p/googletest/wiki/V1_7_AdvancedGuide#Generating_an_XML_Report

**Comment by lookeypl** [comment]
If it is possible, please make it multiplatform. Right now we are in the middle of migration to Linux, so develop Windows version first. Patches enabling nfCommon and nfCommonTest compilation under Linux should be sent today evening to review.

**Comment by lookeypl** [comment]
Oh, and about Colorama - if it's possible, I would avoid using external libraries. Our goal is to reduce the number of external dependencies as much as possible (external = these, which you have to additionally download and install on your PC, not these which compile as a part of nfEngineDeps repo).

**Comment by lookeypl** [comment]
If it's possible, please in future issues you will do, post a link to a change you made on GerritHub. It will make accessing the code easier. :)

https://review.gerrithub.io/#/c/216227/

**Comment by lookeypl** [comment]
Merged, closing.
