### ISSUE TITLE
Move some utility functions from nfCore to nfCommon (Windows)

### ISSUE THREAD

**Issue by Witek902** [nfprojects/nfengine#104]
Functions to move:
- ReadHardwareInfo() @ Engine.cpp
- MemoryCheck() @ Memory.cpp

Write tests as well

**Comment by lookeypl** [comment]
I suggest adding some unit tests (if possible, I did not look into the code) to this unit.

**Comment by mkulagowski** [comment]
https://review.gerrithub.io/#/c/231137/

**Comment by lookeypl** [comment]
Merged, closing. GJ!
