### ISSUE TITLE
Implement Linux version of nfCommon Window module

### ISSUE THREAD

**Issue by lookeypl** [nfprojects/nfengine#106]
nfCommon supports Window creation, however this works only on Windows platform.
- Extract platform-specific code similarly to other platform-specific nfCommon modules (ex. Timer)
- Implement tests if possible (create and close window, do some checks if window is correct). Try to avoid creating platform-specific tests.
- Implement Linux version of Window class. Keep in mind, on some systems X might be replaced with Wayland (check if API is common and if not, appropriately support it).

**Comment by mkulagowski** [comment]
Prepare Window class for porting:
https://review.gerrithub.io/#/c/229157/

Implement linux version of Window:
https://review.gerrithub.io/#/c/229158/

**Comment by lookeypl** [comment]
Merged, closing.
