### ISSUE TITLE
Implement Linux version of nfCommon Input/OutputStream modules

### ISSUE THREAD

**Issue by lookeypl** [nfprojects/nfengine#108]
nfCommon has a module for Input/Output Stream handling, however it is purely implemented under Windows.
- Implement tests. Avoid creating platform-specific tests.
- Rewrite FileInput/OutputStream to use File/FileSystem utilities created by @Witek902 
- Make sure that code is compileable and works under Linux (update CMakeLists)

**Comment by mkulagowski** [comment]
This issue is wrong, IOStream should be wrapper to our File class and buffer operations.
It means that FileInputStream should be rewritten - that's all.

...tests would be nice as well :P

**Comment by lookeypl** [comment]
Updated

**Comment by mkulagowski** [comment]
Refactor: https://review.gerrithub.io/#/c/230637/

Tests: https://review.gerrithub.io/#/c/230236/

**Comment by lookeypl** [comment]
Merged, closing. GJ!
