### ISSUE TITLE
Fix enum class constant name style

### ISSUE THREAD

**Issue by lookeypl** [nfprojects/nfengine#111]
Some enum classes use UpperCamelCase to name its variables, however some use UPPERCASE only. Switch UPPERCASE variables to UpperCamelCase for style consistency.

**Comment by mkulagowski** [comment]
I've searched for enums in our solution and those had UPPERCASE:
1. nfCommon/Image.hpp/ImageFormat
2. nfCore/Resource.hpp/ResourceType
3. nfEngine/Renderers/RendererInterface/Types.hpp/BufferAccess (not entirely, yet i don't think it's completely correct CamelCase.

**Comment by mkulagowski** [comment]
https://review.gerrithub.io/#/c/230363/

**Comment by lookeypl** [comment]
Merged, closing. GJ!
