### ISSUE TITLE
Implement Library module in nfCommon

### ISSUE THREAD

**Issue by lookeypl** [nfprojects/nfengine#114]
Right now, when accessing a specific renderer (on new nfRenderer implementation), we use Windows-specific LoadLibrary function to load the renderer we want. As with the rest of the project, multi-platform solution is needed here. Write Library (name subject to change) module with following features:
- Loading a library with specified name (maybe provide the extension according to current platform? .dll for Windows, .so for Linux <- needs discussion)
- ~~Callback extraction from library for user to call later on~~
- Unit tests for the module (to test module functionality, a small sample library might be needed as well)

**Comment by Witek902** [comment]
https://review.gerrithub.io/#/c/230052/

**Comment by lookeypl** [comment]
What about other points? It would be nice to finish this task already. Maybe someone else will finish it, if you have other tasks to do?

**Comment by mkulagowski** [comment]
Rest:
https://review.gerrithub.io/#/c/233849/
