### ISSUE TITLE
Implement System Info module in nfCommon

### ISSUE THREAD

**Issue by lookeypl** [nfprojects/nfengine#115]
Engine must know information about hardware and software on which it is running. Right now such feature is implemented in a minimal form, in nfCore.
- Move existing functions in nfCore, which extract System information, to nfCommon "SystemInfo" module. (see #104 )
- Enhance Windows version and implement Linux version of System Info module:
  - CPU info extraction (brand name, number of available cores, frequency, cache amount, cache line size, available extensions - see __cpuid function, plus some platform-specific functions)
  - RAM info extraction (total physical amount, total virtual amount, total free amount)
- Write unit tests

**Comment by mkulagowski** [comment]
For Windows i suppose it could be:
-GetProcessMemoryInfo (https://msdn.microsoft.com/en-us/library/ms683219.aspx)
-GetPerformanceInfo (https://msdn.microsoft.com/en-us/library/ms683210(v=vs.85).aspx)

As for linux...maybe getrusage (http://linux.die.net/man/2/getrusage) or sysinfo (http://linux.die.net/man/2/sysinfo)?

Here we can find some ideas to start from:
http://stackoverflow.com/questions/63166/how-to-determine-cpu-and-memory-consumption-from-inside-a-process

**Comment by lookeypl** [comment]
Windows is done - see Engine.cpp inside nfCore. This needs to be moved to nfCommon and maybe extended with missing information, which is not listed above.

For Linux, it looks like these functions might be good. Unfortunately, I cannot 100% check it right now.

**Comment by mkulagowski** [comment]
I wasn't sure about Windows, so we're good.
For getrusage there may be some problems for linuxes with kernel versions before 2.6.9.

If we don't need to worry about this, then choice of function used will be just a matter of convenience.

**Comment by lookeypl** [comment]
2.6.9 is a prehistory. People use it only on servers where there is only one rule - "if it works, do not upgrade". Consumer-grade Linux systems (like Ubuntu) are waaay past 2.6.9 (AFAIK Ubuntu 14.04 LTS is now at 3.13), so I think this is not a problem for us.

**Comment by lookeypl** [comment]
Part of this task will be done as a #104 . Updated description and title.

**Comment by mkulagowski** [comment]
There are some things that interest me:
1. unit tests are also part of #104, so I'm not sure if we need them in this issue
2. up till now ReadHardwareInfo() returned void and all it did was use LOG_INFO to print system information. Is this form satisfactory? 
While extending Windows version & implementing linux one, I can change it to some more approachable way if needed.

**Comment by Witek902** [comment]
ad. 2. No. There should be introduced a structure which will hold all the information so it will be accessible by other parts of the engine.

**Comment by mkulagowski** [comment]
I found quite a useful article about cpuid usage under WIN/Linux:
http://newbiz.github.io/cpp/2010/12/20/Playing-with-cpuid.html
Unfortunately we need more, but for that I will look while implementing.

**Comment by mkulagowski** [comment]
https://review.gerrithub.io/#/c/232046/

**Comment by mkulagowski** [comment]
We need to make up our minds about virtual memory.
What I have done:
-move functions from nfCore
-enhance Windows version
-implement Linux version
-add unit tests

As for now "Virtual Memory" is swap - this has proven to be invalid for Windows users, when swap is disabled (even though I'm using MSDN functions).
Yet afaik, the "Virtual Memory" we're looking for is an actual memory used by our process.

Please clarify this, so I can finally bring this issue to closure.

**Comment by Witek902** [comment]
What do you mean by " this has proven to be invalid for Windows users, when swap is disabled (even though I'm using MSDN functions)."?

**Comment by mkulagowski** [comment]
Well...if total swap is equal 0, then available swap should be equal 0 as well.
Unfortunately Windows ( https://msdn.microsoft.com/en-us/library/windows/desktop/aa366770(v=vs.85).aspx ) haven't foresaw this.
If ull*PageFile is RAM + swap, then when swap is disabled, these values ought to be equal to ull*Phys, which is incorrect for ullAvailPageFile (it's smaller then ullAvailPhys).

As for the sentence from parenthesis...I just hoped that if it's API from such a powerful company, it'd work flawlessly :P

**Comment by lookeypl** [comment]
> As for the sentence from parenthesis...I just hoped that if it's API from such a powerful company, it'd work flawlessly :P

You still have much to learn, young Padawan... ;)

**Comment by lookeypl** [comment]
Okay, here's my suggestion to the problem.

The difference between AvailPage and AvailPhys can be negative, so try to avoid that - if AvailPage is less than AvailPhys, just set it to 0 on our SystemInfo fields. Same for TotalPage/Phys. And, of course, leave a comment about it. What do you think about this workaround?

**Comment by mkulagowski** [comment]
I looked for some solution & this is what I've found:
1. For Windows it should be [GetProcessMemoryInfo](https://msdn.microsoft.com/en-us/library/windows/desktop/ms683219%28v=vs.85%29.aspx)
2. For Linux it should be [getrusage](http://linux.die.net/man/2/getrusage) and unfortunately reading _proc/self/_ files
3. Some implementations and usages can be found [HERE](http://stackoverflow.com/questions/669438/how-to-get-memory-usage-at-run-time-in-c)

I'm afraid that a lot of information we need (MemoryCheck module) in Linux is placed in files in _proc/self/_. Reading those files is slow, yet I'm not sure if we have another option :/

**Comment by mkulagowski** [comment]
Merged. Please close.
