### ISSUE TITLE
Remove SetUpCurrentDirectory functions in engine tests/demos

### ISSUE THREAD

**Issue by Witek902** [nfprojects/nfengine#117]
Almost in every engine test and demo application there is a function SetUpCurrentDirectory() (or simmilar) which changes working directory to nfEngine's root. Find these functions and rewrite them to be cross-platform (FileSystem class should be used).

**Comment by mkulagowski** [comment]
https://review.gerrithub.io/#/c/235997/

**Comment by lookeypl** [comment]
GJ
