### ISSUE TITLE
Exception handling

### ISSUE THREAD

**Issue by lookeypl** [nfprojects/nfengine#120]
Engine has multiple places, where error/exception handling and informing is just plainly terrible, if it exists at all. The project needs an exception system, which would handle all the errors both fast, and with all the needed informations.

**Example locations, which need to be fixed (feel free to add your places):**
- [x] Linux/Window.cpp:34 - move XOpenDisplay call to a method called separately
- [ ] Win/Window.cpp - move error-prone functions (RegisterClass etc) to a method which would return the error
- [ ] Search through what "git grep LOG_ERROR" returns. This should reveal more than enough places to correct the error handling.

**The task is huge and requires some planning, so it needs discussion. Any approved ideas should appear on the list below:**
- _to be filled..._

**Comment by mkulagowski** [comment]
How about each place near LOG_ERROR? I'm almost sure that 1-3 lines after this log we can find return -1 or false or sth.
Apart from that I think we should split that task - one part could be nfCommon, which on it's own is quite a piece of code.

**Comment by lookeypl** [comment]
Good idea @mkulagowski, added.

As for ideas, we should avoid try/catch blocks. These are slow and in realtime there might be some situations, which might cause an error, but the engine will be able to carry on after that (missing textures/models etc). Maybe regular errors should be handled by a code, but criticals should throw to leave from engine's loop?

**Comment by Witek902** [comment]
I recommend reading this (everything):
http://bitsquid.blogspot.com/2012/01/sensible-error-handling-part-1.html
http://bitsquid.blogspot.com/2012/02/sensible-error-handling-part-2.html
http://bitsquid.blogspot.com/2012/02/sensible-error-handling-part-3.html

**Comment by lookeypl** [comment]
Part 2 and 3 does not exist - could you update the links to correct ones?

**Comment by Witek902** [comment]
Done

**Comment by Witek902** [comment]
As a first step of this task I suggest replacing all return values form "enum class Result" to "bool" and removing the "Result" enum class in Core.hpp.

**Comment by mkulagowski** [comment]
This was discussed on the last meet. 
Functions that do not return anything, but their result may be important should return bool.
All other forms of 'error' types should be abolished (meaning the likes of "Result" enum class from Core.hpp).
LOG_ERRORs should be used as well, though there has been no problem with that.

Due to **NOT** designing any new exception system, this task is no longer huge - now it revolves around resolving issues in Window, which will probably be solved with #181 and finding eventual weird return types.
