### ISSUE TITLE
Migrate project to Visual Studio 2015

### ISSUE THREAD

**Issue by Witek902** [nfprojects/nfengine#130]

**Comment by lookeypl** [comment]
I know this is low priority, but is there something in VS2015 that is missing in VS2013 and is absolutely crucial to nfEngine development process?

**Comment by lookeypl** [comment]
Okay, since I installed Windows 10 today and have only VS 2015 available, I think that the migration should occur ASAP. I'll do it.

**Comment by lookeypl** [comment]
Deps: https://review.gerrithub.io/#/c/243914/
Engine: https://review.gerrithub.io/#/c/243922/

**Comment by lookeypl** [comment]
Merged, closing
