### ISSUE TITLE
Implement "Thread" helper class

### ISSUE THREAD

**Issue by Witek902** [nfprojects/nfengine#138]
STL's std::thread is very limited. There are some missing platform-dependent, features:
- retrieving real Thread ID (OS specific)
- setting thread priority
- setting thread's debug name

Consider using thread local storage (TLS) to improve performance.

We can aquire native thread handle with std::thread::native_handle. The API could look like:

```
class Thread {
static bool SetThreadPriority(std::thread& thread);
static int GetCurrentThreadID();
...
};
```

**Comment by mkulagowski** [comment]
in review: [commit](https://review.gerrithub.io/#/c/280956/)

**Comment by mkulagowski** [comment]
Done, close it.
