### ISSUE TITLE
Implement custom config files handling

### ISSUE THREAD

**Issue by Witek902** [nfprojects/nfengine#140]
At the moment, the engine is using JSON for configuration files, but it has two drawbacks:
- it is too verbose (quotes, commas, etc.)
- it does not support comments

New syntax concept:

```
// this is a comment
integerValue = 1
hexValue = 0xFF
booleanValue = true
floatValue = 10.0f
stringValue = "this is a string"
arrayOfFloats = [1.0f, 2.0f, 3.0f]
object =
{
    aaa = 1
}
arrayOfObjects = 
[
    { a = 1, b = 3 }
    { a = 2, b = "aaa" }
]
/* multiline
comment */
```

TODO:
- [x] Config parsing:
  - [x] Simple variable types: integers, floats, booleans, strings
  - [x] Complex variable type (object)
  - [x] Arrays of simple types
  - [x] Arrays of objects (objects in the array do not require to have the same structure)
  - [x] Comments
  - [x] Handling multiple variables with the same name (for now, only visitor should access them).
- [x] Config variables access:
  - [x] via path, for example: `int value = config.GetInt("objects/aaa");``
  - [x] via visitor (a callback function that is called for each config node and value)
  - [x] via something like DataTranslator here: http://blog.molecular-matters.com/2014/01/23/translating-a-human-readable-json-like-data-format-into-c-structs/ - a structure that maps config objects with C++ structure
- [x] Config modification/generation
- [x] Write simple tests
- [x] Document the Config file format and syntax on Wiki pages

Note that config parser should be optimized. Avoid using STL strings. When parsing a config (from a string), there is no need to allocate separate strings for string variables - you just put null termination after the substring you are interested in and return a pointer.

**Comment by lookeypl** [comment]
Sounds like a fun idea. After #26 is done in huge part (ex. all nfRendererDemo scenes will work) I'll be happy to try myself with the issue. :)

**Comment by lookeypl** [comment]
Added one more important point about the task - documentation. We need to describe how config files are created and what the syntax is.

**Comment by Witek902** [comment]
Wiki: https://github.com/nfprojects/nfengine/wiki/nfCommon-Config
