### ISSUE TITLE
Common: Rewrite AlignedAllocator class

### ISSUE THREAD

**Issue by lookeypl** [nfprojects/nfengine#162]
In Aligned.hpp header there is a template class called `AlignedAllocator`. Its source was taken from [a gist](https://gist.github.com/donny-dont/1471329) and we might not have rights to the code. Plus, it uses exceptions, which we do not support in the engine due to performance.

Rewrite AlignedAllocator, add tests if needed.

**Comment by Witek902** [comment]
Will be removed after full migration to nfCommon containers.
