### ISSUE TITLE
Logger performance tests

### ISSUE THREAD

**Issue by Witek902** [nfprojects/nfengine#165]
Scenarios:
- Logging simplest logs possible (eg. single character)
- Logging messages with multiple printf-like arguments (eg. `%i%i%i%i%s%s%s`)
- Logging messages with multiple stream-like arguments (eg. `<< 1 << 2 << 3 << 4 << "a" << "b"`)
- Logging very long messages (longer than `SHORT_MESSAGE_LENGTH`, see https://github.com/nfprojects/nfengine/blob/devel/nfEngine/nfCommon/Logger.cpp#L107)

Each scenario should run fast (about one second in Debug build should be fine).

**Comment by mkulagowski** [comment]
[Here](https://github.com/nfprojects/nfengine/commit/a8a27af8824cce413e4a703ba225d12034612155) and [here](https://github.com/nfprojects/nfengine/commit/acdf9f948c42e5249939443bd6eeee12d1c5c021).

Close?
