### ISSUE TITLE
Fix formatting script

### ISSUE THREAD

**Issue by Witek902** [nfprojects/nfengine#23]
- Formatting script (format.bat) does not work well for SceneManager.h - for example "Camera\* pCamera" is turned into "Camera \* pCamera".
- Namespaces structure should be indented in Prerequisites.h to improve readability.

**Comment by lookeypl** [comment]
Additional issues:
- Missing support for *.hpp files
- Scripts avoid entire nfCommon and nfCommonTest directory
- Scripts work only when launched from Scripts directory

**Comment by lookeypl** [comment]
SceneManager.h error is caused by using NFE_ALIGNED_CLASS macro. I tried to fix it, however with no luck. I guess this must be left now as it is, I'll report a bug to astyle Sourceforge.

**Comment by lookeypl** [comment]
https://review.gerrithub.io/12381
https://review.gerrithub.io/12382

**Comment by lookeypl** [comment]
Merged, closing.
