### ISSUE TITLE
Introduce OpenGL renderer backend

### ISSUE THREAD

**Issue by Witek902** [nfprojects/nfengine#26]
Features to implement:
- [x] Vertex Buffers
- [x] Constant Buffers
- [x] Shader compilation
  - [x] Macros support
  - [ ] Getting Shader bytecode
  - [ ] Getting Shader disassembly
- [x] Vertex Layout
- [x] textures:
  - [ ] 1D, 2D, 3D, Cube
  - [ ] Texture Layers
  - [ ] Multisample Textures
  - [ ] Block Compressed formats
- [x] Backbuffers
  - [x] V-Sync
  - [ ] Fullscreen
- [x] Render Targets
  - [x] Multiple Render Targets (MRT)
  - [ ] 2D Texture layer as a target
  - [ ] 3D Texture slice as a target
  - [ ] Mipmap selection
- [x] Texture Samplers
- [x] Depth Buffers
- [x] Stencil Buffers
- [ ] Unordered Access Views
- [ ] Compute Shaders
- [ ] Tessellation Primitive Topologies
- [x] Indexed Rendering
- [x] Instanced Rendering
- [ ] Dynamic resources (copy from CPU to GPU)
- [ ] Resources readback (copy from GPU to CPU)
- [ ] Geometry shader with Transform Feedback (aka. Stream Output in D3D)
- [x] Multisampling support (+ resolving)
- [ ] Multithreading:
  - [ ] Concurrent resources creation
  - [ ] Creating and using multiple Command Buffers from multiple threads
  - [ ] Executing pre-generated Command Buffers
- [ ] Querying GPU/API capabilities
  - [ ] Available display modes, monitors
  - [ ] Maximum Shader Model level supported
- [ ] Querying stats (see ID3D11Query)
- [ ] Resources copying
- [ ] Scissors
- [ ] Debugging support
  - [ ] Resources naming

**Comment by lookeypl** [comment]
Differences between OGL and D3D resource binding to shaders:
![img_1088](https://cloud.githubusercontent.com/assets/8372811/11177836/b3b35a32-8c48-11e5-8da2-aa2ef2195445.JPG)
