### ISSUE TITLE
Add missing information to README file

### ISSUE THREAD

**Issue by lookeypl** [nfprojects/nfengine#30]
README file has some missing information about the project:
- Provide info about workflow, issue tracking etc.
- Fill TODO section in main description
- Add basic coding guidelines to FORMATTING section

**Comment by lookeypl** [comment]
README updated except for TODO in INTRODUCTION section.

@Witek902 can you write TODO and commit it to update_readme branch?

**Comment by Witek902** [comment]
We should write the README file in Markdown style. See: https://help.github.com/articles/github-flavored-markdown

**Comment by lookeypl** [comment]
OK, I will correct this tomorrow.

**Comment by lookeypl** [comment]
I wrote README file in Markdown, however on main project page GitHub still reads this as plain text. To not waste the Markdown code I made, I created an [introductory wiki page](https://github.com/nfprojects/nfengine/wiki/Introduction) which contains same information as README file, but in formatted version.

**Comment by lookeypl** [comment]
Commits merged. Closing.
