### ISSUE TITLE
Write Linux-specific part of Packer code

### ISSUE THREAD

**Issue by lookeypl** [nfprojects/nfengine#44]
Packer has some platform-specific part inside (ex. recursively adding files to archive). Write these parts under Linux. Use unit-tests as a reference point.

**Comment by lookeypl** [comment]
This hugely relates to #21

Converting Packer to use our multi-platform filesystem utilities should solve the issue.

**Comment by mkulagowski** [comment]
https://review.gerrithub.io/#/c/233817/

**Comment by lookeypl** [comment]
Taking back the task - Packer tests are not built. Enabling them causes build break on Linux (Ubuntu 14.04 x86_64).

**Comment by lookeypl** [comment]
https://review.gerrithub.io/#/c/234701/

Merged, closing.
