### ISSUE TITLE
Port nfCore to linux

### ISSUE THREAD

**Issue by Witek902** [nfprojects/nfengine#52]
This task can be done, when OpenGL renderer is ready.
- Implement missing linux implementations.
- Build nfCore, tests and demo (nfEngineTest) with gcc/clang.
- Verify.

**Comment by lookeypl** [comment]
This might be overly huge task. I suggest to divide it into sub-tasks (like with nfCommon) and group them all together into one "Port nfCore to Linux" milestone.

**Comment by Witek902** [comment]
My mistake, closing.
