### ISSUE TITLE
Create pre-commit script

### ISSUE THREAD

**Issue by Witek902** [nfprojects/nfengine#59]
After #23, #57 and #58 are done, prepare a script that will:
- run static code analysis and print problems (if any)
- run AStyle in dry-run mode and print files that would be modified
- run tests and print results (there also should be a script that runs the tests in all configurations - it could be used during development)

If any of those tests generates an error/warning/problem the commit should be fixed before pushing.

**Comment by lookeypl** [comment]
https://review.gerrithub.io/#/c/13907/

Merged, closing.
