### ISSUE TITLE
Introduce Direct3D 11 renderer backend

### ISSUE THREAD

**Issue by Witek902** [nfprojects/nfengine#60]
Features to implement:
- [x] Vertex Buffers
- [x] Constant Buffers
- [x] Shader compilation
  - [x] Macros support
  - [ ] Getting Shader bytecode
  - [x] Getting Shader disassembly
- [x] Vertex Layout
- [ ] textures:
  - [ ] 1D
  - [x] 2D
  - [ ] 3D
  - [x] Cube
  - [ ] Texture Layers
  - [ ] Multisample Textures
  - [x] Block Compressed formats
- [x] Backbuffers
  - [ ] V-Sync
  - [ ] Fullscreen
- [x] Render Targets
  - [x] Multiple Render Targets (MRT)
  - [ ] 2D Texture layer as a target
  - [ ] 3D Texture slice as a target
  - [ ] Mipmap selection
- [x] Texture Samplers
- [x] Depth Buffers
- [x] Stencil Buffers
- [ ] Unordered Access Views
- [ ] Compute Shaders
- [ ] Tessellation Primitive Topologies
- [x] Indexed Rendering
- [x] Instanced Rendering
- [x] Dynamic resources (copy from CPU to GPU)
- [ ] Resources readback (copy from GPU to CPU)
- [ ] Geometry shader with Stream Output
- [ ] Multisampling support (+ resolving)
- [x] Multithreading:
  - [x] Concurrent resources creation
  - [x] Creating and using multiple Command Buffers from multiple threads
  - [x] Executing pre-generated Command Buffers
- [ ] Querying GPU/API capabilities
  - [ ] Available display modes, monitors
  - [ ] Maximum Shader Model level supported
- [ ] Querying stats (see ID3D11Query)
- [ ] Resources copying
- [ ] Scissors
- [x] Debugging support
  - [x] Resources naming

**Comment by lookeypl** [comment]
There were many commits implementing the issue. More features will be added on 'as-needed' basis. Closing.
