### ISSUE TITLE
Rewrite highlevel renderer

### ISSUE THREAD

**Issue by Witek902** [nfprojects/nfengine#61]
This task can be done only if one of #26 and #60 is (almost) ready.

Move high-level renderer parts from existing RendererD3D11 (nfEngine/nfRenderer) project to the Core. The renderer will use backend API (OpenGL, Direct3D). Provide needed shaders for both APIs. Further changes and new features (in backed API / high-level renderer) should have their own issues.

The following things should be implemented:
- Debug Renderer (simple shapes and textured meshes)
- GBuffer Renderer (single layer textures - as it was)
- Lights Renderer (spot, point and dir lights; no tile-based, fog, etc.)
- Shadows Rendererer (very similar to GBuffer Renderer - maybe merge?)
- Postprocess Renderer (simple tonemapping and gamma-correction only)

**Comment by lookeypl** [comment]
To avoid shader code duplication, we must consider doing something similar to https://docs.unrealengine.com/latest/INT/Programming/Rendering/ShaderDevelopment/HLSLCrossCompiler/index.html

IMO at first this won't be necessary, however in the future this wil greatly help us.

**Comment by Witek902** [comment]
I suggest following workflow for this issue:
1. Create stub classes in nfCore (such as GBufferRenderer, LightsRenderer, etc.) and stop using nfRenderer (old D3D11 renderer library). This will require some modifications in nfCore (approx. commit size will be 2000 LOC). After this step nfEngineTest should work - only blank window will be displayed.
2. Rewrite high-level renderer from scratch using low-level renderer API - this will be the huge part of the task (at least 10k LOC) and will be divided into subissues.
3. Remove nfRenderer (old D3D11 renderer library).

**Comment by Witek902** [comment]
https://review.gerrithub.io/#/c/234304/

**Comment by Witek902** [comment]
Renderer parts described in the task has been rewritten. Other features will have own issues. Closing.
