### ISSUE TITLE
Fix formatting scripts

### ISSUE THREAD

**Issue by lookeypl** [nfprojects/nfengine#80]
Right now formatting scripts have following issues:
- Missing support for *.hpp files
- Scripts avoid entire nfCommon and nfCommonTest directory
- Scripts work only when launched from Scripts directory

Fix these issues (if possible with first two points, make it as generic as possible - use find in sh script and corresponding function in batch script). In separate commit run these scripts to keep formatting constant.

**Comment by Witek902** [comment]
There is dedicated task for it: #23 :)
Move your notes there.
