### ISSUE TITLE
Move nfEngine dependencies from gdrive to Git repository

### ISSUE THREAD

**Issue by lookeypl** [nfprojects/nfengine#91]
We need to move nfEngineDeps folder kept on gdrive to nfprojects/deps repository. Reasons for doing so:
- There is no easy way to download deps - Google Drive has random errors when zipping entire directory with ~2k files for download. One must use Google Drive application at all times.
- No history tracking on google drive - sometimes it would be nice to track changes on our dependencies (eg. library version bump, or minor patches).
- No Linux support in Google Drive - there is no official application for gdrive synchronization on Linux. One must either download all files manually (which is impossible, see my first reason), or use external applications which either don't work on shared folders (grive), or require payments (InSync).
- Git submodules was made for such repositories. Even though not all deps are kept with source code (some of them are precompiled), it would be easier to just enter nfEngine directory and type "git submodules init" instead of jumping between gdrive, linking directories etc.
- If we would be stubborn, inside it we would be able to make more submodules linking to official dependencies repos and checkout them to specific version tags, which would make our work even better.

Keep in mind, this is only about nfEngineDeps. nfEngineTestData would stay as it is right now on Google Drive. Additionally, move Deps to separate solution to avoid rebuilding dependencies together with nfCommon/nfCore. If possible, while doing this task try to minimize issues above - the solution to this problem must take minimal amount of work for newcomers.

**Comment by Witek902** [comment]
As I rethinked it, that's a good idea. Moreover, let's create Visual Studio's solution "nfEngineDeps" inside the new repo, which will collect all project currently located at nfEngine/Deps (zlib, libpng, FreeType) + Bullet. We don't want to recompile those every time we do "Rebuild" for any engine's project. This way we'll get rid of any binary files in git repo.

**Comment by lookeypl** [comment]
OK, I'm moving away proposal label.

**Comment by lookeypl** [comment]
Merged, closing.
