### ISSUE TITLE
Repair link to google drive with dependencies

### ISSUE THREAD

**Issue by mkulagowski** [nfprojects/nfengine#92]
Link to google drive in readme is not working.
There is no way to obtain dependencies required to build engine.

Broken link:
https://drive.google.com/drive/u/0/#folders/0B66mya2agFOEd0RJUWx1aDZ6Ym8

**Comment by lookeypl** [comment]
OK, we'll look into that

**Comment by lookeypl** [comment]
https://review.gerrithub.io/#/c/12941

Merged
