### ISSUE TITLE
Switch to UTF-8 coding

### ISSUE THREAD

**Issue by Witek902** [nfprojects/nfengine#95]
Character coding is inconsistent. Most of the code uses "char*", but some parts (especially Windows-related) use wchar_t. Use UTF-8 coding as the engine's standard. Keep in mind that some conversions may be needed (for example in fonts rendering).

Useful links:
- http://utf8everywhere.org/
- http://www.joelonsoftware.com/articles/Unicode.html

**Comment by mkulagowski** [comment]
How about using TCHARs?
- http://www.codeproject.com/Articles/76252/What-are-TCHAR-WCHAR-LPSTR-LPWSTR-LPCTSTR-etc
- https://msdn.microsoft.com/en-us/library/office/cc842072.aspx

or should we just stick to using wchar_t and L" "?

**Comment by Witek902** [comment]
Generally, for all WinAPI calls we should only use wchar_t (WCHAR) characters. If project is compiled with option "Use Unicode Character Set" (it is as I remember) then wchar_t == TCHAR, so you can use it. But, I would stick to wchar_t just to be sure. Everywhere else (object names, log messages, file names and path, etc.) we should use UTF-8 only (char).

Check this commit to see how I've done UTF-8<==>Window's "Unicode" translation:
https://review.gerrithub.io/#/c/217602/

**Comment by mkulagowski** [comment]
This issue has been taken care of while doing:
https://github.com/nfprojects/nfengine/milestones/Port%20nfCommon%20to%20Linux

When (#106) and (#108) are closed, this issue can be closed as well imho.

What are Your thoughts in this matter, @Witek902 ?

**Comment by Witek902** [comment]
One more place, where UTF-8 is not handled is text rendering. However, this will be rewritten completely this summer (I hope).

**Comment by lookeypl** [comment]
Legacy text rendering was removed together with legacy nfRenderer removal. New text renderer, when implemented, will consider this. Closing.
