### ISSUE TITLE
Complete README file

### ISSUE THREAD

**Issue by Witek902** [nfprojects/nfengine#96]
Things left to write:
- Short engine description
- Coding style:
  - variables, functions naming
  - doxygen comments
- Information about files structure (short description what is in each directory)

**Comment by lookeypl** [comment]
It would be good to update wiki pages as well. Consider splitting this info to multiple files to avoid huge README file.

**Comment by lookeypl** [comment]
README.md merged. I'll update wiki as well, closing.
