### ISSUE TITLE
Update all scripts

### ISSUE THREAD

**Issue by Witek902** [nfprojects/nfengine#97]
Things to be done:
- Scripts assume that they are launched when being in Scripts directory (except for format.bat) - some solution similar to the one in format.bat must be made to launch them from anywhere
- format.bat indeed must be rewritten to bash

This task should be done before #59 and only after this is finished any additions to engine utility scripts can be done.

**Comment by lookeypl** [comment]
I think this task should be more generic - "Update scripts" or sth.

Things to be done:
- Scripts assume that they are launched when being in Scripts directory (except for format.bat) - some solution similar to the one in format.bat must be made to launch them from anywhere
- format.bat indeed must be rewritten to bash

As a remark, I think this task should be done before #59 and only after this is finished any additions to engine utility scripts can be done.

**Comment by lookeypl** [comment]
Batch update: https://review.gerrithub.io/#/c/13837/
Bash update: https://review.gerrithub.io/#/c/13861/

**Comment by lookeypl** [comment]
Merged, closing.
