### ISSUE TITLE
Remove all useless #if ... #else ... #endif sections

### ISSUE THREAD

**Issue by lookeypl** [nfprojects/nfengine#98]
Some parts of engine have code hidden by #if ... #else ... #endif sequence. Search for all of them and either remove them, or provide different way to determine which section to use (avoid preprocessor macros, we want the engine to be entirely compiled).

**Comment by mkulagowski** [comment]
I've searched our repo for #endif's and apart from few platform dependencies in headers, I've found this:
&bull;`_DEBUG`
&bull;`NFE_MATH_USE_SSE`
&bull;`NFE_ALIGN(a)`
&bull;`_CRTDBG_MAP_ALLOC`
&bull;`Logger macros`     **(Logger should be ported to linux properly)**
&bull;`MAKEFOURCC`
&bull;`INSTANCING`
&bull;`CORE_EXPORTS`
&bull;`FileTest.cpp`     **#if defined(WIN32) in test?!**
&bull;`USE_ANT_TWEAK`

Could You guys take a look at this (if you're not sure what that is, just search it - should be easy to find) and think what can be target of this issue?

**Comment by lookeypl** [comment]
OK, thanks for the research. Here's what I know:

"if defined" in FileTest.cpp - this is an ultra-specific corner case, which had to be allowed during review. See a comment above this "if defined" sentence.

Logger will be rewritten, so current code will be trashed. Issue #2 is there and I'll take care of it sometime soon.

_CRTDBG_MAP_ALLOC must stay - this is a macro, which is used by VS Profiler, which we use from time to time.

CORE_EXPORTS is an old macro. IMO it should be removed, because Engine uses NF_CORE_EXPORTS.

NFE_ALIGN is a macro used to mark, that specific class/structure must be aligned to x bytes. This needs to stay.

As for the other parts, we will have to discuss what to do and how to do it.

**Comment by lookeypl** [comment]
All old macros were removed during refactoring of specific Engine parts. Issue can be closed now.
